language: generic

os: osx
osx_image: xcode11.4

rvm:
- 2.7

env:
- TRAVIS_TAG="Deploy-test" PROJECT_NAME="AFKScapePakage" UNITY_PROJECT_PATH="AFKScape" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - unity_download_cache
    - /home/travis/.rvm/

    
before_install:
    - chmod -R a+rw ./unity_download_cache
    - chmod a+x ./travis-build/*.sh

install:
    - ./travis-build/install-unity.sh
 
jobs:
    include:        
        - stage: "Build"
        - script: ./travis-build/build.sh
        
        - stage: "Unit Tests"
        - script: ./travis-build/run-unit-tests.sh
