language: generic

os: osx
osx_image: xcode11.4

rvm:
- 2.7

git:
  depth: 3


  #could be slower this rem
cache:
  directories:
    - unity_download_cache

    
before_install:
  - chmod -R a+rw ./unity_download_cache
  - chmod a+x ./travis-build/*.sh

install:
  - ./travis-build/install-unity.sh

script:
  - ./travis-build/build.sh
  - ./travis-build/run-unit-tests.sh

env:
  global:
  - UNITY_NOPROXY="localhost,127.0.0.1"
  - UNITY_DOWNLOAD_CACHE="${TRAVIS_BUILD_DIR}/unity_download_cache"
  - UNITY_PROJECT_NAME="UnityProject"
  - BUILD_PATH="${TRAVIS_BUILD_DIR}/Builds"
  - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"