language: generic

os: osx
osx_image: xcode11.4

rvm:
- 2.7

git:
  depth: 3


cache:
  directories:
    - unity_download_cache

    
before_install:
  - chmod -R a+rw ./unity_download_cache
  - chmod a+x ./travis-build/*.sh


stages:
  - "Install Unity"
  - build
  - tests


jobs:
  include:
    - stage: "Install Unity"
      install: ./travis-build/install-unity.sh
    - stage: build
      script: ./travis-build/build.sh
      
    - stage: tests
      script: ./travis-build/run-unit-tests.sh

env:
    global:
    - UNITY_PROJECT_PATH="AFKScape"
