language: objective-c
osx_image: xcode11.4
rvm:
- 2.7

env:
- TRAVIS_TAG="Deploy-test" PROJECT_NAME="AFKScapePakage" UNITY_PROJECT_PATH="AFKScape" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE
     - /home/travis/.rvm/

    
before_install:
- chmod a+x ./travis-build/*.sh

jobs:
    - stage "Install Unity"
    install:
    - ./travis-build/install-unity.sh
    
    - stage "Build"
    script:
    - ./travis-build/build.sh
    
    - stage "Unit Tests"
    script:
    - ./travis-build/run-unit-tests.sh
