name: Main Checks

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - AFKScape
        unityVersion:
          - 2019.3.7f1
        testMode:
          - editmode
          - playmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      - uses: actions/cache@v1.2.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
            
      - uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: testReports/${{ matrix.testMode }}
      
      # Install dotnet
      - name: Installing dotnet
        if: always()
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.202'
      # Do the report magic
      - name: Generate .html report
        run: sudo dotnet ./Tools/ExtentReports/ExtentReportsDotNetCLI.dll -i=testReports/${{ matrix.testMode }}/${{ matrix.testMode }}-results.xml -o testReports/${{ matrix.testMode }}/
        if: always()
        
      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: testReports 
  
  stylecop:
    name: Style Cop
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.7f1
    strategy:
      matrix:
        projectPath:
          - AFKScape

    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
          
      - uses: actions/cache@v1.2.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
          
      # Install dotnet
      - name: Installing dotnet
        if: always()
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      
      # 
      - name: Dependencies
        run: |
          apt-get update
          apt-get install -y mono-devel
          export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/Current
      
      - name: Create License file
        run: 'echo "$UNITY_LICENSE" > license.ulf'
        
      - name: Set-up Unity
        run: sh ./Scripts/unity-set-up.sh
        
      - name: Run Style-Cop
        if: always()
        run: sh ./Scripts/run-style-cop.sh

  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - AFKScape
        unityVersion:
          - 2019.3.7f1
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.2.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v0.15
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
